# Generated by Django 5.0.1 on 2024-02-02 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_rename_product_recipe_products'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='recipeproduct',
            constraint=models.UniqueConstraint(fields=('recipe', 'product'), name='unique_product_for_recipe'),
        ),
    ]
